Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Failed to run custom action 'inform_form_2'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form_2'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Couldn't create message for template 'utter_greet'.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_greet'.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'inform_form'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'inform_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/naoko/projects/rasa_bots/rasa_core/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Rasa process starting
Rasa process starting
Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/naoko/projects/rasa_bots/venv/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, OPTIONS, HEAD             /static/[filename]
custom_webhook_CmdlineInput.health                 GET, OPTIONS, HEAD             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.957897424697876}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	distance: None
	finish_time: None
	main_menu: None
	next_race_distance: None
	predicted_finish_time_result: None
	race_strategy_result: None
	requested_slot: None
	target_pace_result: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '4'
There is no active form
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hello! I'm your test bot <3, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '5'
There is no active form
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_show_menu' with prob 1.00.
Action 'utter_show_menu' ended with events '[]'
Bot utterance 'BotUttered(text: Select one of the options below., data: {
  "elements": null,
  "buttons": [
    {
      "payload": "/select_menu_item{\"main_menu\":\"target\"}",
      "title": "Target Pace"
    },
    {
      "payload": "/select_menu_item{\"main_menu\":\"strategy\"}",
      "title": "Race Strategy"
    },
    {
      "payload": "/select_menu_item{\"main_menu\":\"predicted\"}",
      "title": "Predicted Finish Time"
    }
  ],
  "attachment": null
})'
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_show_menu': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
